version: '3.5'
services:
   mavenwebapp:
     image: lokeshsdockerhub/mavenwebapp:VERSION
     ports:
     - 9090:8080
     networks:
     - mavenwebappbridge
networks:
  mavenwebappbridge:
    driver: bridge
