services:
   mavenwebapplication:
     image: lokeshsdockerhub/mavenwebapplication:version
     ports:
     - 9090:8080
     networks:
     - mavenwebappbridge
networks:
  mavenwebappbridge:
    driver: bridge
 
