version: '3.5'
services:
   mavenwebapplication:
     image: lokeshsdockerhub/mavenwebapplication:version
     ports:
     - 9090:8080
     networks:
     - mavenwebappbridge
     volumes:
     - /home/ubuntu/mavenwebappvol:/usr/local/tomcat/webapps
networks:
  mavenwebappbridge:
    driver: bridge
volumes:
  mavenwebappvol:
    driver: local
   