apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp
spec:
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: lokeshsdockerhub/mavenwebapp:TAG
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mavenwebappvol
          mountPath: /data/db
      volumes:
      - name: mavenwebappvol
        nfs:
          server: 172.31.34.88
          path: /mnt/nfs_share
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mavenwebapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mavenwebapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
